/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

import javax.swing.JFrame;
public class Interfaz extends JFrame {
Calculadorapa cal = new Calculadorapa();
boolean inic=true;
boolean primnum=true;
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        Sum = new javax.swing.JButton();
        Res = new javax.swing.JButton();
        Mult = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Igual = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        Div = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        Seno = new javax.swing.JButton();
        Coseno = new javax.swing.JButton();
        Tangente = new javax.swing.JButton();
        Punto = new javax.swing.JButton();
        Raiz = new javax.swing.JButton();
        Potencia = new javax.swing.JButton();
        Iva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Calculadora"));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        Sum.setText("Sumar");
        Sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumActionPerformed(evt);
            }
        });

        Res.setText("Restar");
        Res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResActionPerformed(evt);
            }
        });

        Mult.setText("Multiplicar");
        Mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultActionPerformed(evt);
            }
        });

        Igual.setText("=");
        Igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IgualActionPerformed(evt);
            }
        });

        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.setText("5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b8.setText("8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b9.setText("9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        b0.setText("0");
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });

        Div.setText("Dividir");
        Div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivActionPerformed(evt);
            }
        });

        jButton6.setText("Limpiar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        Seno.setText("Seno");
        Seno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenoActionPerformed(evt);
            }
        });

        Coseno.setText("Coseno");
        Coseno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CosenoActionPerformed(evt);
            }
        });

        Tangente.setText("Tangente");
        Tangente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TangenteActionPerformed(evt);
            }
        });

        Punto.setText(".");
        Punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PuntoActionPerformed(evt);
            }
        });

        Raiz.setText("Raiz n");
        Raiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RaizActionPerformed(evt);
            }
        });

        Potencia.setText("Potencia n");
        Potencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PotenciaActionPerformed(evt);
            }
        });

        Iva.setText("IVA");
        Iva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IvaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(226, 226, 226))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(b8, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                    .addComponent(Punto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Igual, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                    .addComponent(b9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jButton6))
                                .addGap(18, 18, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Mult, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Iva))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Sum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Raiz))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Res)
                                        .addGap(18, 18, 18)
                                        .addComponent(Potencia))
                                    .addComponent(Coseno)
                                    .addComponent(Tangente)
                                    .addComponent(Div)
                                    .addComponent(Seno))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sum)
                    .addComponent(b1)
                    .addComponent(b2)
                    .addComponent(b3)
                    .addComponent(Raiz))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b4)
                            .addComponent(b5)
                            .addComponent(b6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b7)
                            .addComponent(b8)
                            .addComponent(b9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b0)
                            .addComponent(Igual)
                            .addComponent(Punto))
                        .addGap(26, 26, 26)
                        .addComponent(jButton6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Res)
                            .addComponent(Potencia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Mult)
                            .addComponent(Iva))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Div)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Seno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Coseno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tangente)))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
    public void divcero(){
    if(cal.res==34404){
        jTextField1.setText("Error(division entre 0)");
        jLabel1.setText(""); 
    }
    }
    private void SumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumActionPerformed
        //suma
        primnum=true;
        if(inic){
            cal.n1=Double.parseDouble(jTextField1.getText());
        cal.opc1=1;
        jTextField1.setText("");
        inic=false;
        jLabel1.setText(String.valueOf(cal.n1) +"+");
        }
        else{
           cal.n2=Double.parseDouble(jTextField1.getText());
           cal.res=cal.opcion(cal.opc1,cal.n1,cal.n2);
           cal.n1=cal.res;
           cal.opc1=1;
            jTextField1.setText(String.valueOf(cal.n1));
            
           jLabel1.setText(String.valueOf(cal.n1) +"+"); 
        }
        divcero();
    }//GEN-LAST:event_SumActionPerformed

    private void ResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResActionPerformed
        //restar
        primnum=true;
        if(inic){
            cal.n1=Double.parseDouble(jTextField1.getText());
        cal.opc1=2;
        jTextField1.setText("");
        inic=false;
        jLabel1.setText(String.valueOf(cal.n1) +"-");
        }
        else{
            jLabel1.setText("-");
           cal.n2=Double.parseDouble(jTextField1.getText());
           cal.res=cal.opcion(cal.opc1,cal.n1,cal.n2);
           cal.n1=cal.res;
           cal.opc1=2;
            jTextField1.setText(String.valueOf(cal.n1));
            divcero();
           jLabel1.setText(String.valueOf(cal.n1) +"-"); 
        }
        divcero();
    }//GEN-LAST:event_ResActionPerformed

    private void IgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IgualActionPerformed
        primnum=true;
        cal.n2=Double.parseDouble(jTextField1.getText());
        cal.res=cal.opcion(cal.opc1,cal.n1,cal.n2);
        jTextField1.setText(String.valueOf(cal.res));
        jLabel1.setText("");
        inic=true;
        divcero();
    }//GEN-LAST:event_IgualActionPerformed
    
    private void MultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultActionPerformed
        primnum=true;
        if(inic){
            cal.n1=Double.parseDouble(jTextField1.getText());
        cal.opc1=3;
        jTextField1.setText("");
        inic=false;
        jLabel1.setText(String.valueOf(cal.n1) +" X ");
        }
        else{
            jLabel1.setText("-");
           cal.n2=Double.parseDouble(jTextField1.getText());
           cal.res=cal.opcion(cal.opc1,cal.n1,cal.n2);
           cal.n1=cal.res;
           cal.opc1=3;
            jTextField1.setText(String.valueOf(cal.n1));
           jLabel1.setText(String.valueOf(cal.n1) +" X "); 
        }
        divcero();
    }//GEN-LAST:event_MultActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        if(primnum){
            jTextField1.setText("1");
            primnum=false;
        }
        else{
            jTextField1.setText(this.jTextField1.getText()+"1");
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        if(primnum){
            jTextField1.setText("2");
            primnum=false;
        }
        else{
            jTextField1.setText(this.jTextField1.getText()+"2");
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        if(primnum){
            jTextField1.setText("3");
            primnum=false;
        }
        else{
            jTextField1.setText(this.jTextField1.getText()+"3");
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        if(primnum){
            jTextField1.setText("4");
            primnum=false;
        }
        else{
            jTextField1.setText(this.jTextField1.getText()+"4");
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
       if(primnum){
            jTextField1.setText("5");
            primnum=false;
        }
        else{
            jTextField1.setText(this.jTextField1.getText()+"5");
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        if(primnum){
            jTextField1.setText("6");
            primnum=false;
        }
        else{
            jTextField1.setText(this.jTextField1.getText()+"6");
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        if(primnum){
            jTextField1.setText("7");
            primnum=false;
        }
        else{
            jTextField1.setText(this.jTextField1.getText()+"7");
        }
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        if(primnum){
            jTextField1.setText("8");
            primnum=false;
        }
        else{
            jTextField1.setText(this.jTextField1.getText()+"8");
        }
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        if(primnum){
            jTextField1.setText("9");
            primnum=false;
        }
        else{
            jTextField1.setText(this.jTextField1.getText()+"9");
        }
    }//GEN-LAST:event_b9ActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        if(primnum){
            jTextField1.setText("0");
            primnum=false;
        }
        else{
            jTextField1.setText(this.jTextField1.getText()+"0");
        }
    }//GEN-LAST:event_b0ActionPerformed

    private void DivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivActionPerformed
        primnum=true;
        if(inic){
            cal.n1=Double.parseDouble(jTextField1.getText());
        cal.opc1=4;
        jTextField1.setText("");
        inic=false;
        jLabel1.setText(String.valueOf(cal.n1) +" / ");
        }
        else{
            jLabel1.setText("-");
           cal.n2=Double.parseDouble(jTextField1.getText());
           cal.res=cal.opcion(cal.opc1,cal.n1,cal.n2);
           cal.n1=cal.res;
           cal.opc1=4;
            jTextField1.setText(String.valueOf(cal.n1));
           jLabel1.setText(String.valueOf(cal.n1) +" / "); 
        }
        divcero();
    }//GEN-LAST:event_DivActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jTextField1.setText("");
           jLabel1.setText(""); 
        inic=true;
        primnum=true;
    }//GEN-LAST:event_jButton6ActionPerformed

    private void SenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenoActionPerformed
        primnum=true;
        if(inic){
        cal.n2=Double.parseDouble(jTextField1.getText());
        jLabel1.setText( " SEN "+String.valueOf(cal.n2)+"°");
        cal.opc1=5;
        jTextField1.setText(String.valueOf(cal.opcion(cal.opc1,cal.n1,cal.n2)));
        inic=false;
        
        }
        else{
            jLabel1.setText("-");
           cal.n2=Double.parseDouble(jTextField1.getText());
           jLabel1.setText( " SEN "+String.valueOf(cal.n2)+"°");
           cal.opc1=5;
           cal.res=cal.opcion(cal.opc1,cal.n1,cal.n2);
           cal.n2=cal.res;
           
            jTextField1.setText(String.valueOf(cal.n2));
            
        }
    }//GEN-LAST:event_SenoActionPerformed

    private void CosenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CosenoActionPerformed
        primnum=true;
        if(inic){
        cal.n2=Double.parseDouble(jTextField1.getText());
        jLabel1.setText(" COS "+String.valueOf(cal.n2)+"°");
        cal.opc1=6;
        jTextField1.setText(String.valueOf(cal.opcion(cal.opc1,cal.n1,cal.n2)));
        inic=false;
        
        }
        else{
            jLabel1.setText("-");
           cal.n2=Double.parseDouble(jTextField1.getText());
           jLabel1.setText(" COS "+String.valueOf(cal.n2)+"°");
           cal.opc1=6;
           cal.res=cal.opcion(cal.opc1,cal.n1,cal.n2);
           cal.n2=cal.res;
           
            jTextField1.setText(String.valueOf(cal.n2));
           
        }
    }//GEN-LAST:event_CosenoActionPerformed

    private void TangenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TangenteActionPerformed
        primnum=true;
        if(inic){
        cal.n2=Double.parseDouble(jTextField1.getText());
        jLabel1.setText(" TAN "+String.valueOf(cal.n2)+"°");
        cal.opc1=7;
        jTextField1.setText(String.valueOf(cal.opcion(cal.opc1,cal.n1,cal.n2)));
        inic=false;
        
        }
        else{
            jLabel1.setText("-");
           cal.n2=Double.parseDouble(jTextField1.getText());
           jLabel1.setText(" TAN "+String.valueOf(cal.n2)+"°");
           cal.opc1=7;
           cal.res=cal.opcion(cal.opc1,cal.n1,cal.n2);
           cal.n2=cal.res;
           
            jTextField1.setText(String.valueOf(cal.n2));
           
        }
        
    }//GEN-LAST:event_TangenteActionPerformed

    private void PuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PuntoActionPerformed
        if(primnum){
            jTextField1.setText(".");
            primnum=false;
        }
        else{
            jTextField1.setText(this.jTextField1.getText()+".");
        }
    }//GEN-LAST:event_PuntoActionPerformed

    private void RaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RaizActionPerformed
        primnum=true;
        if(inic){
            cal.n1=Double.parseDouble(jTextField1.getText());
        cal.opc1=8;
        jTextField1.setText("Indice:");
        inic=false;
        jLabel1.setText(" √ "+String.valueOf(cal.n1) );
        }
        else{
            jLabel1.setText("-");
           cal.n2=Double.parseDouble(jTextField1.getText());
           cal.res=cal.opcion(cal.opc1,cal.n1,cal.n2);
           cal.n1=cal.res;
           cal.opc1=8;
            jTextField1.setText("Indice:");
           jLabel1.setText(" √ "+String.valueOf(cal.n1)); 
        }
        divcero();
    }//GEN-LAST:event_RaizActionPerformed

    private void PotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PotenciaActionPerformed
        primnum=true;
        if(inic){
            cal.n1=Double.parseDouble(jTextField1.getText());
        cal.opc1=9;
        jTextField1.setText("Exponente:");
        inic=false;
        jLabel1.setText(String.valueOf(cal.n1)+"^" );
        }
        else{
            jLabel1.setText("-");
           cal.n2=Double.parseDouble(jTextField1.getText());
           cal.res=cal.opcion(cal.opc1,cal.n1,cal.n2);
           cal.n1=cal.res;
           cal.opc1=9;
            jTextField1.setText("Exponente:");
           jLabel1.setText(String.valueOf(cal.n1)+"^"); 
        }
        divcero();
    }//GEN-LAST:event_PotenciaActionPerformed

    private void IvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IvaActionPerformed
        primnum=true;
        if(inic){
            cal.n1=Double.parseDouble(jTextField1.getText());
        cal.opc1=10;
        jTextField1.setText("Porcentaje:");
        inic=false;
        jLabel1.setText(String.valueOf(cal.n1)+" IV" );
        }
        else{
            jLabel1.setText("-");
           cal.n2=Double.parseDouble(jTextField1.getText());
           cal.res=cal.opcion(cal.opc1,cal.n1,cal.n2);
           cal.n1=cal.res;
           cal.opc1=10;
            jTextField1.setText("Porcentaje:");
           jLabel1.setText(String.valueOf(cal.n1)+" IV"); 
        }
        divcero();
    }//GEN-LAST:event_IvaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Coseno;
    private javax.swing.JButton Div;
    private javax.swing.JButton Igual;
    private javax.swing.JButton Iva;
    private javax.swing.JButton Mult;
    private javax.swing.JButton Potencia;
    private javax.swing.JButton Punto;
    private javax.swing.JButton Raiz;
    private javax.swing.JButton Res;
    private javax.swing.JButton Seno;
    private javax.swing.JButton Sum;
    private javax.swing.JButton Tangente;
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
